default:
  image: node:18

stages:
  - test
  - deploy-staging
  - deploy-production

test-job:
  stage: test
  script:
    - npm ci
    - npm run build
    - npm run check
    - npm run lint
    - npm run test:unit

deploy-staging-job:
  stage: deploy-staging
  only:
    - master
  environment:
    name: staging
    url: https://rodeo-nightly.freetailhackers.com/
  script:
    - npx vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - mv .vercel/.env.preview.local .env # Needed for prisma migrate deploy
    - "export $(grep -v '^#' .env | xargs)" # Needed to correctly set $DOMAIN_NAME
    - npx prisma migrate deploy
    - npx vercel deploy --token=$VERCEL_TOKEN > domain.txt
    - npx vercel alias --token=$VERCEL_TOKEN set `cat domain.txt` `echo $DOMAIN_NAME | awk -F// '{print $NF}'` # Must remove https:// for vercel alias to work
    - rm .env domain.txt

deploy-production-job:
  stage: deploy-production
  only:
    - master
  environment:
    name: production
    url: https://rodeo.freetailhackers.com/
  when: manual
  script:
    - npx vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - mv .vercel/.env.production.local .env # Needed for prisma migrate deploy
    - "export $(grep -v '^#' .env | xargs)" # Needed to correctly set $DOMAIN_NAME
    - npx prisma migrate deploy
    - npx vercel deploy --prod --token=$VERCEL_TOKEN > domain.txt
    - npx vercel alias --token=$VERCEL_TOKEN set `cat domain.txt` $(echo $DOMAIN_NAME | awk -F// '{print $NF}') # Must remove https:// for vercel alias to work
    - rm .env domain.txt
