default:
  image: node

stages:
  - build
  - test
  - deploy

build-job:
  stage: build
  script:
    - npm ci
    - npm run build

unit-test-job:
  stage: test
  script:
    - npm ci
    - npm run test:unit
    - npm run test

lint-test-job:
  stage: test
  script:
    - npm ci
    - npm run lint

deploy-job:
  stage: deploy
  environment: production
  script:
    - echo "Deploying application..."
    - echo "Application successfully deployed."
