default:
  image: node:18

stages:
  - test
  - deploy

test-job:
  stage: test
  except:
    - production
  script:
    - npm ci
    - npm run check
    - npm run lint
    - npm run test:unit

deploy_staging:
  stage: deploy
  variables:
    STAGING_URL: rodeo-staging.freetailhackers.com
  only:
    - master
  environment:
    name: staging
    url: $STAGING_URL
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - cp .vercel/.env.preview.local .env
    - npx prisma migrate deploy
    - vercel deploy --token=$VERCEL_TOKEN
    - vercel alias --token=$VERCEL_TOKEN set https://rodeo-freetail-hackers.vercel.app/ $STAGING_URL

deploy_production:
  stage: deploy
  variables:
    PROD_URL: rodeo.freetailhackers.com
    DEPLOYMENT_URL: https://rodeo.freetailhackers.com/
  only:
    - production
  environment:
    name: production
    url: $PROD_URL
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - cp .vercel/.env.production.local .env
    - npx prisma migrate deploy
    - vercel deploy --prod --token=$VERCEL_TOKEN
    - vercel alias --token=$VERCEL_TOKEN set $DEPLOYMENT_URL $PROD_URL
