default:
  image: node:18

stages:
  - test
  - deploy

test-job:
  stage: test
  except:
    - production
  script:
    - npm ci
    - npm run check
    - npm run lint
    - npm run test:unit

deploy_staging:
  stage: deploy
  only:
    - master
  environment:
    name: preview
    url: https://rodeo-staging.freetailhackers.com/
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=preview --token=$VERCEL_TOKEN
    - cp .vercel/.env.preview.local .env
    - npx prisma migrate deploy
    - vercel deploy --token=$VERCEL_TOKEN

deploy_production:
  stage: deploy
  only:
    - production
  environment:
    name: production
    url: https://rodeo.freetailhackers.com/
  script:
    - npm install --global vercel
    - vercel pull --yes --environment=production --token=$VERCEL_TOKEN
    - cp .vercel/.env.production.local .env
    - npx prisma migrate deploy
    - vercel deploy --prod --token=$VERCEL_TOKEN
